meta:
  device: 'cuda:0'

stft:
  n_fft: 512
  hop_length: 256

train:
  epochs: 500
  batch_size: 64
  num_workers: 5
  learning_rate: 0.0001
  frame_weighting_factor: 1
  validate_every_n_epochs: 5

model:
  cnn_channels: [32, 64, 128, 256]
  cnn_kernel_size: 3
  blstm_hidden_size: 128
  fc_hidden_size: 128
  fc_dropout: 0.3